/-
# The bounded-generator Laplace resolvent identity

Moved from `manhattan-formalization` (`Manhattan.Operator.Semigroup`), where it
formalized the classical Hille-Yosida / Green-Kubo resolvent-as-Laplace-
transform identity for a bounded generator, fully abstractly: `E` is an
arbitrary complex Hilbert space and `G : E →L[ℂ] E` is any bounded operator
whose exponential `operatorSemigroup G` is a contraction at nonnegative times.

For such a `G` and `lambda > 0`, the Bochner integral of the exponentially
damped orbit `t ↦ exp(-lambda t) • operatorSemigroup G t u` (the "Laplace
vector") is shown to be the bounded two-sided inverse of `lambda I - G`
(`resolventOperator_laplaceVector`, `laplaceVector_resolventOperator`). Taking
an inner product against `u` gives the scalar Green-Kubo identity
`∫₀^∞ e^{-lambda t} ⟪u, T(t) u⟫ dt = ⟪u, (lambda I - G)⁻¹ u⟫`
(`integral_inner_operatorSemigroup_eq_resolvent`), the standard route from a
contraction semigroup to resolvent bounds. Nothing here refers to any
particular lattice or model; it is the bounded-generator special case of
Lumer-Phillips / Hille-Yosida semigroup theory, and is built to match the
generator language of `LatticeProb.Analysis.DissipativeSkewOperator`.
-/
import Mathlib.Analysis.Calculus.Deriv.Mul
import Mathlib.Analysis.InnerProductSpace.Adjoint
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.SpecialFunctions.ImproperIntegrals
import Mathlib.MeasureTheory.Integral.IntegralEqImproper

noncomputable section

open ComplexConjugate InnerProductSpace MeasureTheory NormedSpace RCLike
open scoped ComplexConjugate InnerProduct

namespace LatticeProb.Analysis

variable {E : Type*} [NormedAddCommGroup E]
  [InnerProductSpace ℂ E] [CompleteSpace E]

/-- The complex space read as a real normed space. -/
local instance : NormedSpace ℝ E := NormedSpace.restrictScalars ℝ ℂ E

/-- The uniformly continuous semigroup generated by a bounded operator. -/
def operatorSemigroup (G : E →L[ℂ] E) (t : ℝ) : E →L[ℂ] E :=
  NormedSpace.exp (t • G)

/-- The operator `lambda I - G`. -/
def resolventOperator (G : E →L[ℂ] E) (lambda : ℝ) : E →L[ℂ] E :=
  lambda • ContinuousLinearMap.id ℂ E - G

/-- An exponentially damped semigroup orbit. -/
def dampedOrbit (G : E →L[ℂ] E) (lambda : ℝ) (u : E) (t : ℝ) : E :=
  Real.exp (-lambda * t) • operatorSemigroup G t u

/-- The vector-valued Laplace transform of a semigroup orbit. -/
def laplaceVector (G : E →L[ℂ] E) (lambda : ℝ) (u : E) : E :=
  ∫ t in Set.Ioi 0, dampedOrbit G lambda u t

/-- The semigroup orbit through `u` has derivative `G` applied to itself. -/
theorem operatorSemigroup_hasDerivAt (G : E →L[ℂ] E) (u : E) (t : ℝ) :
    HasDerivAt (fun s : ℝ ↦ operatorSemigroup G s u)
      (G (operatorSemigroup G t u)) t := by
  let ev : (E →L[ℂ] E) →L[ℝ] E :=
    (ContinuousLinearMap.apply ℂ E u).restrictScalars ℝ
  have hexp := hasFDerivAt_exp_smul_const' (𝕂 := ℝ) G t
  have h := (ev.hasFDerivAt.comp t hexp).hasDerivAt
  simpa [ev, operatorSemigroup, Function.comp_def] using h

omit [CompleteSpace E] in
/-- The generator commutes with its own semigroup. -/
theorem generator_commutes_operatorSemigroup (G : E →L[ℂ] E) (t : ℝ) :
    Commute G (operatorSemigroup G t) := by
  apply Commute.exp_right
  exact (Commute.refl G).smul_right t

/-- The damped orbit solves `x' = -(lambda I - G) x`. -/
theorem dampedOrbit_hasDerivAt (G : E →L[ℂ] E) (lambda t : ℝ) (u : E) :
    HasDerivAt (dampedOrbit G lambda u)
      (-resolventOperator G lambda (dampedOrbit G lambda u t)) t := by
  have hs : HasDerivAt (fun s : ℝ ↦ Real.exp (-lambda * s))
      (-lambda * Real.exp (-lambda * t)) t := by
    have h0 : HasDerivAt (fun s : ℝ => -lambda * s) (-lambda) t := by
      simpa using (hasDerivAt_id t).const_mul (-lambda)
    simpa [mul_comm] using h0.exp
  have ho := operatorSemigroup_hasDerivAt G u t
  have hcomb := hs.smul ho
  have heq1 : (fun s => Real.exp (-lambda * s)) • (fun s => operatorSemigroup G s u)
      = dampedOrbit G lambda u := rfl
  rw [heq1] at hcomb
  convert hcomb using 1
  simp only [resolventOperator, dampedOrbit, sub_apply,
    smul_apply, ContinuousLinearMap.id_apply,
    ContinuousLinearMap.map_smul_of_tower, neg_sub, smul_smul]
  module

omit [CompleteSpace E] in
/-- If the semigroup is contractive at nonnegative times, the damped orbit is
bounded by the damping factor. -/
theorem dampedOrbit_norm_le (G : E →L[ℂ] E) (lambda : ℝ) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1)
    {t : ℝ} (ht : 0 ≤ t) :
    ‖dampedOrbit G lambda u t‖ ≤ Real.exp (-lambda * t) * ‖u‖ := by
  rw [dampedOrbit, norm_smul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  gcongr
  exact (ContinuousLinearMap.le_opNorm _ _).trans
    (mul_le_of_le_one_left (norm_nonneg u) (hcontract t ht))

/-- The damped orbit is integrable on `(0, ∞)` once `lambda > 0` and the
semigroup is a contraction. -/
theorem integrableOn_dampedOrbit (G : E →L[ℂ] E) {lambda : ℝ} (hlambda : 0 < lambda)
    (u : E) (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    IntegrableOn (dampedOrbit G lambda u) (Set.Ioi 0) := by
  apply Integrable.mono'
    ((integrableOn_exp_mul_Ioi (a := -lambda) (by linarith) 0).mul_const ‖u‖)
  · exact (continuous_iff_continuousAt.2 fun t ↦
      (dampedOrbit_hasDerivAt G lambda t u).continuousAt).aestronglyMeasurable
  · filter_upwards [ae_restrict_mem measurableSet_Ioi] with t ht
    simpa only [neg_mul] using dampedOrbit_norm_le G lambda u hcontract ht.le

omit [CompleteSpace E] in
/-- The damped orbit decays to zero at infinity. -/
theorem tendsto_dampedOrbit_atTop (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    Filter.Tendsto (dampedOrbit G lambda u) Filter.atTop (nhds 0) := by
  rw [Metric.tendsto_atTop]
  intro epsilon hepsilon
  have hexp : Filter.Tendsto (fun t : ℝ ↦ Real.exp (-lambda * t) * ‖u‖)
      Filter.atTop (nhds 0) := by
    have h := (Real.tendsto_exp_neg_atTop_nhds_zero.comp
      (Filter.tendsto_id.const_mul_atTop hlambda)).mul_const ‖u‖
    simpa only [Function.comp_apply, id_eq, zero_mul, neg_mul] using h
  rw [Metric.tendsto_atTop] at hexp
  obtain ⟨a, ha⟩ := hexp epsilon hepsilon
  refine ⟨max a 0, fun b hb ↦ ?_⟩
  rw [dist_zero_right]
  exact (dampedOrbit_norm_le G lambda u hcontract (le_trans (le_max_right _ _) hb)).trans_lt
    (by simpa [dist_zero_right] using ha b (le_trans (le_max_left _ _) hb))

/-- `resolventOperator` applied to the damped orbit is also integrable. -/
theorem integrableOn_resolvent_dampedOrbit (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    IntegrableOn (fun t ↦ resolventOperator G lambda (dampedOrbit G lambda u t))
      (Set.Ioi 0) :=
  (resolventOperator G lambda).integrable_comp
    (integrableOn_dampedOrbit G hlambda u hcontract)

/-- The Laplace vector is a right inverse for `lambda I - G`. -/
theorem resolventOperator_laplaceVector (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    resolventOperator G lambda (laplaceVector G lambda u) = u := by
  have hFTC := integral_Ioi_of_hasDerivAt_of_tendsto'
    (a := (0 : ℝ)) (m := (0 : E))
    (fun t _ ↦ dampedOrbit_hasDerivAt G lambda t u)
    ((integrableOn_resolvent_dampedOrbit G hlambda u hcontract).neg)
    (tendsto_dampedOrbit_atTop G hlambda u hcontract)
  rw [integral_neg] at hFTC
  rw [laplaceVector, ← ContinuousLinearMap.integral_comp_comm]
  · apply neg_injective
    simpa [dampedOrbit, operatorSemigroup] using hFTC
  exact integrableOn_dampedOrbit G hlambda u hcontract

/-- The Laplace vector is also a left inverse for `lambda I - G`. -/
theorem laplaceVector_resolventOperator (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    laplaceVector G lambda (resolventOperator G lambda u) = u := by
  rw [laplaceVector]
  calc
    ∫ t in Set.Ioi 0, dampedOrbit G lambda (resolventOperator G lambda u) t =
        ∫ t in Set.Ioi 0,
          resolventOperator G lambda (dampedOrbit G lambda u t) := by
            apply integral_congr_ae
            filter_upwards with t
            have hcomm : G (operatorSemigroup G t u) =
                operatorSemigroup G t (G u) := by
              simpa [mul_apply_eq_comp] using
                congrArg (fun T : E →L[ℂ] E ↦ T u)
                  (generator_commutes_operatorSemigroup G t).eq
            have hpoint : operatorSemigroup G t (resolventOperator G lambda u) =
                resolventOperator G lambda (operatorSemigroup G t u) := by
              simp only [resolventOperator, sub_apply,
                smul_apply, ContinuousLinearMap.id_apply, map_sub,
                ContinuousLinearMap.map_smul_of_tower]
              rw [hcomm]
            rw [dampedOrbit, dampedOrbit,
              ContinuousLinearMap.map_smul_of_tower, hpoint]
    _ = resolventOperator G lambda (laplaceVector G lambda u) := by
      rw [laplaceVector, ContinuousLinearMap.integral_comp_comm]
      exact integrableOn_dampedOrbit G hlambda u hcontract
    _ = u := resolventOperator_laplaceVector G hlambda u hcontract

/-- `lambda I - G` is injective for `lambda > 0`, given a contractive
semigroup. -/
theorem resolventOperator_injective (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    Function.Injective (resolventOperator G lambda) := by
  intro u v huv
  rw [← laplaceVector_resolventOperator G hlambda u hcontract,
    ← laplaceVector_resolventOperator G hlambda v hcontract, huv]

/-- `lambda I - G` is bijective for `lambda > 0`, given a contractive
semigroup: the resolvent exists as a bounded operator. -/
theorem resolventOperator_bijective (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    Function.Bijective (resolventOperator G lambda) :=
  ⟨resolventOperator_injective G hlambda hcontract,
    fun u ↦ ⟨laplaceVector G lambda u,
      resolventOperator_laplaceVector G hlambda u hcontract⟩⟩

/-- The bounded equivalence `lambda I - G`, with inverse supplied by the
Laplace transform. -/
def resolventEquiv (G : E →L[ℂ] E) {lambda : ℝ} (hlambda : 0 < lambda)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) : E ≃L[ℂ] E :=
  ContinuousLinearEquiv.ofBijective (resolventOperator G lambda)
    (LinearMap.ker_eq_bot.mpr (resolventOperator_bijective G hlambda hcontract).1)
    (LinearMap.range_eq_top.mpr (resolventOperator_bijective G hlambda hcontract).2)

/-- The inverse of `resolventEquiv` is the Laplace vector map. -/
theorem resolventEquiv_symm_apply (G : E →L[ℂ] E) {lambda : ℝ}
    (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    (resolventEquiv G hlambda hcontract).symm u = laplaceVector G lambda u := by
  apply (resolventEquiv G hlambda hcontract).injective
  simpa [resolventEquiv] using
    (resolventOperator_laplaceVector G hlambda u hcontract).symm

/-- The scalar integrand in the Green-Kubo identity. -/
def semigroupCorrelation (G : E →L[ℂ] E)
    (lambda : ℝ) (u : E) (t : ℝ) : ℂ :=
  (Real.exp (-lambda * t) : ℂ) * ⟪u, operatorSemigroup G t u⟫_ℂ

/-- **The Green-Kubo resolvent identity**, in Bochner-integral form: the
Laplace transform of the semigroup correlation at `u` equals the inner
product of `u` against the resolvent of `G` applied to `u`. -/
theorem integral_inner_operatorSemigroup_eq_resolvent (G : E →L[ℂ] E)
    {lambda : ℝ} (hlambda : 0 < lambda) (u : E)
    (hcontract : ∀ t : ℝ, 0 ≤ t → ‖operatorSemigroup G t‖ ≤ 1) :
    (∫ t in Set.Ioi 0, semigroupCorrelation G lambda u t) =
      ⟪u, (resolventEquiv G hlambda hcontract).symm u⟫_ℂ := by
  rw [resolventEquiv_symm_apply G hlambda u hcontract, laplaceVector]
  change (∫ t in Set.Ioi 0, semigroupCorrelation G lambda u t) =
    (innerSL ℂ u) (∫ t in Set.Ioi 0, dampedOrbit G lambda u t)
  calc
    _ = ∫ t in Set.Ioi 0, (innerSL ℂ u) (dampedOrbit G lambda u t) := by
      apply integral_congr_ae
      filter_upwards with t
      simp [semigroupCorrelation, dampedOrbit]
    _ = _ := ContinuousLinearMap.integral_comp_comm (L := innerSL ℂ u)
      (integrableOn_dampedOrbit G hlambda u hcontract)

end LatticeProb.Analysis
