/-
Disjoint blocks of coordinates of an independent family are independent.

Mathlib has the independence of the single coordinates of `Measure.infinitePi`
and the independence of two blocks of an independent family, but not the
independence of a countable family of disjoint blocks, which is what an argument
that runs many gadgets on disjoint sets of sites needs.  The proof is a
reindexing: reading the family along the disjoint union of the blocks is reading
it along an injective family of indices, so the joint law is the product, and
uncurrying the disjoint union is exactly the grouping.
-/
import Mathlib
import LatticeProb.Prob.FiniteMarginal

noncomputable section

namespace LatticeProb

open MeasureTheory ProbabilityTheory

/-- **Reading an independent family along an injective family of indices.**  The
finite-index version is `LatticeProb.infinitePi_map_comp`; here the index type is
arbitrary. -/
theorem infinitePi_map_comp' {ι α : Type*} [MeasurableSpace α] (ν : Measure α)
    [IsProbabilityMeasure ν] {κ : Type*} (v : κ → ι) (hv : Function.Injective v) :
    (Measure.infinitePi fun _ : ι => ν).map (fun ω k => ω (v k))
      = Measure.infinitePi fun _ : κ => ν := by
  classical
  have hmeas : Measurable (fun (ω : ι → α) (k : κ) => ω (v k)) :=
    measurable_pi_lambda _ fun k => measurable_pi_apply (v k)
  refine Measure.eq_infinitePi (fun _ : κ => ν) fun s t ht => ?_
  set T : ι → Set α := fun i => ⋂ k ∈ s, (if v k = i then t k else Set.univ) with hT
  have hTmeas : ∀ i, MeasurableSet (T i) := by
    intro i
    refine MeasurableSet.biInter (Set.to_countable _) fun k _ => ?_
    by_cases h : v k = i <;> simp [h, ht k]
  have hTv : ∀ k ∈ s, T (v k) = t k := by
    intro k hk
    ext x
    simp only [hT, Set.mem_iInter]
    constructor
    · intro hx
      have := hx k hk
      simpa using this
    · intro hx k' hk'
      by_cases h : v k' = v k
      · rw [if_pos h, hv h]
        exact hx
      · rw [if_neg h]
        trivial
  have hpre : (fun (ω : ι → α) (k : κ) => ω (v k)) ⁻¹' (Set.pi ↑s t)
      = Set.pi ↑(s.image v) T := by
    ext ω
    simp only [Set.mem_preimage, Set.mem_pi, Finset.mem_coe, Finset.mem_image]
    constructor
    · rintro h i ⟨k, hk, rfl⟩
      rw [hTv k hk]
      exact h k hk
    · intro h k hk
      have := h (v k) ⟨k, hk, rfl⟩
      rwa [hTv k hk] at this
  rw [Measure.map_apply hmeas (MeasurableSet.pi (Set.to_countable _) fun k _ => ht k), hpre,
    Measure.infinitePi_pi _ fun i _ => hTmeas i,
    Finset.prod_image fun a _ b _ h => hv h]
  exact Finset.prod_congr rfl fun k hk => by rw [hTv k hk]

/-! ### Disjoint blocks -/

section Blocks

variable {ι V : Type*}

/-- The index in `V` of an element of the disjoint union of the blocks. -/
def blockIndex (A : ι → Set V) (p : (i : ι) × ↥(A i)) : V := (p.2 : V)

theorem blockIndex_injective (A : ι → Set V)
    (hdisj : Pairwise (Function.onFun Disjoint A)) : Function.Injective (blockIndex A) := by
  rintro ⟨i, ⟨x, hx⟩⟩ ⟨j, ⟨y, hy⟩⟩ h
  simp only [blockIndex] at h
  subst h
  have hij : i = j := by
    by_contra hne
    exact Set.disjoint_left.mp (hdisj hne) hx hy
  subst hij
  rfl

/-- **The blocks of an independent family have the product law.** -/
theorem map_blocks (ν : Measure ℝ) [IsProbabilityMeasure ν] (A : ι → Set V)
    (hdisj : Pairwise (Function.onFun Disjoint A)) :
    (Measure.infinitePi fun _ : V => ν).map (fun ω i => (A i).restrict ω)
      = Measure.infinitePi fun i : ι => Measure.infinitePi fun _ : ↥(A i) => ν := by
  have h1 : (Measure.infinitePi fun _ : V => ν).map (fun ω p => ω (blockIndex A p))
      = Measure.infinitePi fun _ : (i : ι) × ↥(A i) => ν :=
    infinitePi_map_comp' ν (blockIndex A) (blockIndex_injective A hdisj)
  have h2 := Measure.infinitePi_map_piCurry (fun (i : ι) (_ : ↥(A i)) => (ν : Measure ℝ))
  have hcomp : (fun (ω : V → ℝ) (i : ι) => (A i).restrict ω)
      = ⇑(MeasurableEquiv.piCurry fun (_ : ι) (_ : ↥(A _)) => ℝ)
        ∘ (fun (ω : V → ℝ) p => ω (blockIndex A p)) := rfl
  rw [hcomp, ← Measure.map_map (MeasurableEquiv.piCurry _).measurable
    (measurable_pi_lambda _ fun p => measurable_pi_apply (blockIndex A p)), h1, h2]

/-- **Disjoint blocks of coordinates are independent.**  Since `iIndepFun` is by
definition the independence of the sigma-algebras generated by the maps, this is
the independence of the block sigma-algebras. -/
theorem iIndepFun_restrict_of_pairwise_disjoint (ν : Measure ℝ) [IsProbabilityMeasure ν]
    (A : ι → Set V) (hdisj : Pairwise (Function.onFun Disjoint A)) :
    ProbabilityTheory.iIndepFun (fun (i : ι) (ω : V → ℝ) => (A i).restrict ω)
      (Measure.infinitePi fun _ : V => ν) := by
  have hm : AEMeasurable (fun (ω : V → ℝ) (i : ι) => (A i).restrict ω)
      (Measure.infinitePi fun _ : V => ν) := by
    refine (measurable_pi_lambda _ fun i => ?_).aemeasurable
    exact measurable_pi_lambda _ fun j => measurable_pi_apply (j : V)
  rw [ProbabilityTheory.iIndepFun_iff_map_fun_eq_infinitePi_map₀ hm, map_blocks ν A hdisj]
  congr 1
  funext i
  exact (Measure.infinitePi_map_restrict' (μ := fun _ : V => ν) (I := A i)).symm

/-- The same statement written as the independence of the block
sigma-algebras. -/
theorem iIndep_comap_of_pairwise_disjoint (ν : Measure ℝ) [IsProbabilityMeasure ν]
    (A : ι → Set V) (hdisj : Pairwise (Function.onFun Disjoint A)) :
    ProbabilityTheory.iIndep
      (fun i : ι => MeasurableSpace.comap (fun ω : V → ℝ => (A i).restrict ω) inferInstance)
      (Measure.infinitePi fun _ : V => ν) :=
  iIndepFun_restrict_of_pairwise_disjoint ν A hdisj

/-- **Events reading disjoint blocks of coordinates are independent.** -/
theorem iIndepSet_of_pairwise_disjoint (ν : Measure ℝ) [IsProbabilityMeasure ν]
    (A : ι → Set V) (hdisj : Pairwise (Function.onFun Disjoint A))
    (E : ι → Set (V → ℝ))
    (hE : ∀ i, MeasurableSet[MeasurableSpace.comap
      (fun ω : V → ℝ => (A i).restrict ω) inferInstance] (E i)) :
    ProbabilityTheory.iIndepSet E (Measure.infinitePi fun _ : V => ν) := by
  rw [ProbabilityTheory.iIndepSet_iff_iIndep]
  refine ProbabilityTheory.iIndep_of_iIndep_of_le
    (iIndep_comap_of_pairwise_disjoint ν A hdisj) fun i => ?_
  exact MeasurableSpace.generateFrom_le fun s hs => by
    rw [Set.mem_singleton_iff] at hs
    exact hs ▸ hE i

end Blocks

end LatticeProb

end
