/-
The strong Markov property of Brownian motion on `ℝ ^ d`.

The statement proved here is `LatticeProb.HasStrongMarkovRestart` for the
natural filtration of a motion whose values are measurable at every time and
whose every path is continuous: for every stopping time `τ`, every event `E` of
the past at `τ` and every measurable set `Γ` of paths, the increments after `τ`
lie in `Γ` with the probability that the centred motion does, independently of
`E`.

The proof is the classical one, in four steps.

At a DETERMINISTIC time the increments after `t₀` are independent of the path up
to `t₀`.  Mathlib has this one coordinate at a time; the vector statement is not
a formal consequence, because the past of the whole motion is generated by all
the coordinates jointly.  It follows from the independence of the coordinates by
`LatticeProb.indepFun_pi_of_pairs`: the pairs (increments after `t₀`, path up to
`t₀`) of the several coordinates are independent of each other, and inside each
pair the two halves are independent, so the two families are independent.

At a stopping time with COUNTABLY MANY VALUES the identity follows by summing the
deterministic one over the values: on the event that the stopping time equals `v`
the restarted path is the path restarted at `v`, and the event `E` intersected
with that event belongs to the filtration at `v`.  The right-hand side does not
depend on `v` because the law of the increments after `v` is the law of the
centred motion, which is `LatticeProb.IsBrownianSpace.map_shift_eq`.

A GENERAL stopping time is approximated from above by `⌈2ⁿ τ⌉ / 2ⁿ`, which takes
countably many values, and the paths are continuous, so the restarted paths
converge.  The laws of the restarted paths are therefore compared through bounded
continuous functions of finitely many coordinates, where convergence of the paths
gives convergence of the integrals by dominated convergence.  Two finite Borel
measures on a finite product of Euclidean spaces that integrate every bounded
continuous function alike are equal, and two measures on path space that agree on
the measurable cylinders are equal, so the two laws on path space agree.

The hypotheses on the motion are the two the argument uses and no more: the value
at each time is measurable, and every path is continuous.  The first is needed
for the natural filtration to exist at all, the second for the restarted path at
a random time to be measurable and for the approximation to converge.
-/
import Mathlib
import LatticeProb.Prob.IndepPi
import LatticeProb.Prob.BrownianPathLaw
import LatticeProb.Prob.StoppingDyadic
import LatticeProb.Prob.BrownianMarkov

open MeasureTheory ProbabilityTheory Filter
open scoped ENNReal NNReal Topology

noncomputable section

namespace LatticeProb

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω}

theorem IsBrownianSpace.indepFun_shift {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hB : IsBrownianSpace d x B P) (hm : ∀ t, Measurable (B t)) (t₀ : ℝ≥0) :
    IndepFun (fun ω (t : ℝ≥0) => B (t₀ + t) ω - B t₀ ω)
      (fun ω (s : Set.Iic t₀) => B (s : ℝ≥0) ω) P := by
  haveI := hB.isProbabilityMeasure
  set c : ℝ := Real.sqrt d with hc
  have hev : ∀ i : Fin d, Measurable fun v : EuclideanSpace ℝ (Fin d) => v i := by
    intro i; fun_prop
  have hcoord : ∀ (t : ℝ≥0) (i : Fin d), Measurable fun ω => B t ω i :=
    fun t i => (hev i).comp (hm t)
  have key : IndepFun
      (fun ω (i : Fin d) => (fun t : ℝ≥0 => c * (B (t₀ + t) ω i - B t₀ ω i)))
      (fun ω (i : Fin d) => (fun s : Set.Iic t₀ => c * (B (s : ℝ≥0) ω i - x i))) P := by
    refine indepFun_pi_of_pairs
      (fun i => measurable_pi_lambda _ fun t => ((hcoord (t₀ + t) i).sub (hcoord t₀ i)).const_mul c)
      (fun i => measurable_pi_lambda _ fun s => ((hcoord (s : ℝ≥0) i).sub measurable_const).const_mul c)
      ?_ (fun i => hB.indepFun_coord_shift t₀ i)
    refine hB.indep.comp
      (fun (i : Fin d) (h : ℝ≥0 → ℝ) =>
        ((fun t : ℝ≥0 => c * (h (t₀ + t) - h t₀)),
          (fun s : Set.Iic t₀ => c * (h (s : ℝ≥0) - x i)))) (fun i => ?_)
    apply Measurable.prodMk
    · refine measurable_pi_lambda _ fun t => ?_
      exact (((measurable_pi_apply (t₀ + t) : Measurable fun h : ℝ≥0 → ℝ => h (t₀ + t))).sub
        ((measurable_pi_apply t₀ : Measurable fun h : ℝ≥0 → ℝ => h t₀))).const_mul c
    · refine measurable_pi_lambda _ fun s => ?_
      exact (((measurable_pi_apply ((s : Set.Iic t₀) : ℝ≥0) :
        Measurable fun h : ℝ≥0 → ℝ => h ((s : Set.Iic t₀) : ℝ≥0))).sub
          measurable_const).const_mul c
  have hφ : Measurable fun u : Fin d → (ℝ≥0 → ℝ) => (fun t : ℝ≥0 =>
      ((EuclideanSpace.equiv (Fin d) ℝ).symm (fun i => c⁻¹ * u i t) :
        EuclideanSpace ℝ (Fin d))) := by
    refine measurable_pi_lambda _ fun t => ?_
    refine ((EuclideanSpace.equiv (Fin d) ℝ).symm.continuous).measurable.comp ?_
    refine measurable_pi_lambda _ fun i => ?_
    exact (((measurable_pi_apply t : Measurable fun h : ℝ≥0 → ℝ => h t)).comp
      ((measurable_pi_apply i : Measurable fun u : Fin d → (ℝ≥0 → ℝ) => u i))).const_mul c⁻¹
  have hψ : Measurable fun v : Fin d → (Set.Iic t₀ → ℝ) => (fun s : Set.Iic t₀ =>
      ((EuclideanSpace.equiv (Fin d) ℝ).symm (fun i => c⁻¹ * v i s + x i) :
        EuclideanSpace ℝ (Fin d))) := by
    refine measurable_pi_lambda _ fun s => ?_
    refine ((EuclideanSpace.equiv (Fin d) ℝ).symm.continuous).measurable.comp ?_
    refine measurable_pi_lambda _ fun i => ?_
    exact ((((measurable_pi_apply s : Measurable fun h : Set.Iic t₀ → ℝ => h s)).comp
      ((measurable_pi_apply i : Measurable fun v : Fin d → (Set.Iic t₀ → ℝ) => v i))).const_mul
        c⁻¹).add_const _
  have hres := key.comp hφ hψ
  have hsymm : ∀ (u : Fin d → ℝ) (i : Fin d),
      ((EuclideanSpace.equiv (Fin d) ℝ).symm u) i = u i := fun _ _ => rfl
  have hcne : ∀ i : Fin d, c ≠ 0 := by
    intro i
    have hd : (0 : ℝ) < d := by exact_mod_cast Fin.pos i
    rw [hc]
    exact (Real.sqrt_pos.2 hd).ne'
  have h1 : (fun u : Fin d → (ℝ≥0 → ℝ) => (fun t : ℝ≥0 =>
        ((EuclideanSpace.equiv (Fin d) ℝ).symm (fun i => c⁻¹ * u i t) :
          EuclideanSpace ℝ (Fin d))))
      ∘ (fun ω (i : Fin d) => (fun t : ℝ≥0 => c * (B (t₀ + t) ω i - B t₀ ω i)))
      = fun ω (t : ℝ≥0) => B (t₀ + t) ω - B t₀ ω := by
    funext ω t
    ext i
    simp only [Function.comp_apply, PiLp.sub_apply, hsymm]
    rw [inv_mul_cancel_left₀ (hcne i)]
  have h2 : (fun v : Fin d → (Set.Iic t₀ → ℝ) => (fun s : Set.Iic t₀ =>
        ((EuclideanSpace.equiv (Fin d) ℝ).symm (fun i => c⁻¹ * v i s + x i) :
          EuclideanSpace ℝ (Fin d))))
      ∘ (fun ω (i : Fin d) => (fun s : Set.Iic t₀ => c * (B (s : ℝ≥0) ω i - x i)))
      = fun ω (s : Set.Iic t₀) => B (s : ℝ≥0) ω := by
    funext ω s
    ext i
    simp only [Function.comp_apply, hsymm]
    rw [inv_mul_cancel_left₀ (hcne i), sub_add_cancel]
  rwa [h1, h2] at hres

omit [MeasurableSpace Ω] in
theorem inter_eq_mem_filtration {m0 : MeasurableSpace Ω}
    {𝔽 : Filtration ℝ≥0 m0} {σ : Ω → ℝ≥0}
    (hσ : IsStoppingTime 𝔽 fun ω => (σ ω : ℝ≥0∞))
    (hcount : (Set.range fun ω => ((σ ω : ℝ≥0) : ℝ≥0∞)).Countable)
    {E : Set Ω} (hE : MeasurableSet[hσ.measurableSpace] E) (v : ℝ≥0) :
    MeasurableSet[𝔽 v] (E ∩ {ω | σ ω = v}) := by
  have hv : MeasurableSet[hσ.measurableSpace] {ω | ((σ ω : ℝ≥0) : ℝ≥0∞) = (v : ℝ≥0∞)} :=
    hσ.measurableSet_eq_of_countable_range' hcount v
  have hset : {ω | σ ω = v} = {ω | ((σ ω : ℝ≥0) : ℝ≥0∞) = (v : ℝ≥0∞)} := by
    ext ω
    simp only [Set.mem_setOf_eq, ENNReal.coe_inj]
  rw [hset]
  exact (hσ.measurableSet_inter_eq_iff _ v).1 (hE.inter hv)

/-- The restart identity at a deterministic time. -/
theorem IsBrownianSpace.restart_const {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hB : IsBrownianSpace d x B P) (hm : ∀ t, StronglyMeasurable (B t)) (v : ℝ≥0)
    {A : Set Ω} (hA : MeasurableSet[natFiltration B hm v] A)
    {Γ : Set (ℝ≥0 → EuclideanSpace ℝ (Fin d))} (hΓ : MeasurableSet Γ) :
    P (A ∩ {ω | (fun t => B (v + t) ω - B v ω) ∈ Γ})
      = P A * P {ω | (fun t => B t ω - B 0 ω) ∈ Γ} := by
  haveI := hB.isProbabilityMeasure
  have hmm : ∀ t, Measurable (B t) := fun t => (hm t).measurable
  have hind := (IndepFun_iff_Indep _ _ _).1 (hB.indepFun_shift hmm v)
  have hAc : MeasurableSet[MeasurableSpace.comap
      (fun ω (s : Set.Iic v) => B (s : ℝ≥0) ω) inferInstance] A := by
    rwa [natFiltration_eq_comap] at hA
  have hΓc : MeasurableSet[MeasurableSpace.comap
      (fun ω (t : ℝ≥0) => B (v + t) ω - B v ω) inferInstance]
      {ω | (fun t => B (v + t) ω - B v ω) ∈ Γ} := ⟨Γ, hΓ, rfl⟩
  have h1 := (Indep_iff _ _ _).1 hind _ _ hΓc hAc
  have hmshift : Measurable fun ω (t : ℝ≥0) => B (v + t) ω - B v ω :=
    measurable_pi_lambda _ fun t => (hmm (v + t)).sub (hmm v)
  have hmshift0 : Measurable fun ω (t : ℝ≥0) => B t ω - B 0 ω :=
    measurable_pi_lambda _ fun t => (hmm t).sub (hmm 0)
  have h2 : P {ω | (fun t => B (v + t) ω - B v ω) ∈ Γ}
      = P {ω | (fun t => B t ω - B 0 ω) ∈ Γ} := by
    show P ((fun ω (t : ℝ≥0) => B (v + t) ω - B v ω) ⁻¹' Γ)
        = P ((fun ω (t : ℝ≥0) => B t ω - B 0 ω) ⁻¹' Γ)
    rw [← Measure.map_apply hmshift hΓ, ← Measure.map_apply hmshift0 hΓ,
      hB.map_shift_eq hmm v]
  rw [Set.inter_comm, h1, h2, mul_comm]

/-- **The restart identity at a stopping time with countably many values.** -/
theorem IsBrownianSpace.restart_countable {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hB : IsBrownianSpace d x B P) (hm : ∀ t, StronglyMeasurable (B t))
    {σ : Ω → ℝ≥0}
    (hσ : IsStoppingTime (natFiltration B hm) fun ω => (σ ω : ℝ≥0∞))
    (hcount : (Set.range fun ω => ((σ ω : ℝ≥0) : ℝ≥0∞)).Countable)
    {E : Set Ω} (hE : MeasurableSet[hσ.measurableSpace] E)
    {Γ : Set (ℝ≥0 → EuclideanSpace ℝ (Fin d))} (hΓ : MeasurableSet Γ) :
    P (E ∩ {ω | (fun t => B (σ ω + t) ω - B (σ ω) ω) ∈ Γ})
      = P E * P {ω | (fun t => B t ω - B 0 ω) ∈ Γ} := by
  haveI := hB.isProbabilityMeasure
  classical
  have hmm : ∀ t, Measurable (B t) := fun t => (hm t).measurable
  have hRc : (Set.range σ).Countable := by
    refine Set.Countable.mono ?_
      (hcount.preimage ENNReal.coe_injective)
    rintro r ⟨ω, rfl⟩
    exact ⟨ω, rfl⟩
  haveI : Countable ↥(Set.range σ) := hRc.to_subtype
  set G : ↥(Set.range σ) → Set Ω := fun v => E ∩ {ω | σ ω = (v : ℝ≥0)} with hGdef
  set S : ↥(Set.range σ) → Set Ω :=
    fun v => {ω | (fun t => B ((v : ℝ≥0) + t) ω - B (v : ℝ≥0) ω) ∈ Γ} with hSdef
  have hG𝔽 : ∀ v : ↥(Set.range σ), MeasurableSet[natFiltration B hm (v : ℝ≥0)] (G v) :=
    fun v => inter_eq_mem_filtration hσ hcount hE (v : ℝ≥0)
  have hGmeas : ∀ v, MeasurableSet (G v) :=
    fun v => (natFiltration B hm).le _ _ (hG𝔽 v)
  have hSmeas : ∀ v, MeasurableSet (S v) := fun v =>
    (measurable_pi_lambda _ fun t => (hmm ((v : ℝ≥0) + t)).sub (hmm (v : ℝ≥0))) hΓ
  have hdisjG : Pairwise (Function.onFun Disjoint G) := by
    intro v w hvw
    refine Set.disjoint_left.2 ?_
    rintro ω ⟨-, hv⟩ ⟨-, hw⟩
    exact hvw (Subtype.ext (hv.symm.trans hw))
  have hdisj : Pairwise (Function.onFun Disjoint fun v => G v ∩ S v) := by
    intro v w hvw
    exact ((hdisjG hvw).mono Set.inter_subset_left Set.inter_subset_left)
  have hunion : E ∩ {ω | (fun t => B (σ ω + t) ω - B (σ ω) ω) ∈ Γ} = ⋃ v, G v ∩ S v := by
    ext ω
    constructor
    · rintro ⟨hEω, hΓω⟩
      exact Set.mem_iUnion.2 ⟨⟨σ ω, ⟨ω, rfl⟩⟩, ⟨hEω, rfl⟩, hΓω⟩
    · intro hω
      obtain ⟨v, ⟨hEω, hvω⟩, hΓω⟩ := Set.mem_iUnion.1 hω
      refine ⟨hEω, ?_⟩
      simp only [Set.mem_setOf_eq] at hΓω ⊢
      rw [hvω]
      exact hΓω
  have hEunion : E = ⋃ v, G v := by
    ext ω
    simp only [Set.mem_iUnion, hGdef, Set.mem_inter_iff, Set.mem_setOf_eq]
    exact ⟨fun hEω => ⟨⟨σ ω, ω, rfl⟩, hEω, rfl⟩, fun ⟨_, hEω, _⟩ => hEω⟩
  rw [hunion, measure_iUnion hdisj (fun v => (hGmeas v).inter (hSmeas v))]
  have hterm : ∀ v, P (G v ∩ S v) = P (G v) * P {ω | (fun t => B t ω - B 0 ω) ∈ Γ} :=
    fun v => hB.restart_const hm (v : ℝ≥0) (hG𝔽 v) hΓ
  rw [tsum_congr hterm, ENNReal.tsum_mul_right, ← measure_iUnion hdisjG hGmeas, ← hEunion]

omit [MeasurableSpace Ω] in
theorem tendsto_shift_dyUp {d : ℕ} {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hcont : ∀ ω, Continuous fun t => B t ω) (τ : Ω → ℝ≥0) (ω : Ω) (t : ℝ≥0) :
    Tendsto (fun n => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω) atTop
      (𝓝 (B (τ ω + t) ω - B (τ ω) ω)) := by
  have h0 : Tendsto (fun n => dyUp n (τ ω)) atTop (𝓝 (τ ω)) := tendsto_dyUp (τ ω)
  have h1 : Tendsto (fun n => dyUp n (τ ω) + t) atTop (𝓝 (τ ω + t)) :=
    h0.add tendsto_const_nhds
  exact (((hcont ω).tendsto (τ ω + t)).comp h1).sub (((hcont ω).tendsto (τ ω)).comp h0)

omit [MeasurableSpace Ω] in
theorem tendsto_restrict_shift_dyUp {d : ℕ} {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hcont : ∀ ω, Continuous fun t => B t ω) (τ : Ω → ℝ≥0) (J : Finset ℝ≥0) (ω : Ω) :
    Tendsto (fun n => J.restrict (fun t => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω)) atTop
      (𝓝 (J.restrict (fun t => B (τ ω + t) ω - B (τ ω) ω))) :=
  tendsto_pi_nhds.2 fun j => tendsto_shift_dyUp hcont τ ω (j : ℝ≥0)

omit [MeasurableSpace Ω] in
/-- A stopping time with values in `ℝ≥0` is a measurable function. -/
theorem measurable_of_isStoppingTime {m0 : MeasurableSpace Ω} {𝔽 : Filtration ℝ≥0 m0}
    {ρ : Ω → ℝ≥0} (hρ : IsStoppingTime 𝔽 fun ω => (ρ ω : ℝ≥0∞)) : Measurable ρ := by
  refine measurable_of_Iic (fun a => ?_)
  have h2 : ρ ⁻¹' Set.Iic a = {ω | ((ρ ω : ℝ≥0) : ℝ≥0∞) ≤ (a : ℝ≥0∞)} := by
    ext ω
    simp only [Set.mem_preimage, Set.mem_Iic, Set.mem_setOf_eq]
    exact ENNReal.coe_le_coe.symm
  rw [h2]
  exact 𝔽.le a _ (hρ a)

/-- The increments of a process with continuous paths after a random time are measurable. -/
theorem measurable_shift_apply {d : ℕ} {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hm : ∀ t, StronglyMeasurable (B t)) (hcont : ∀ ω, Continuous fun t => B t ω)
    {ρ : Ω → ℝ≥0} (hρ : Measurable ρ) :
    Measurable fun ω (t : ℝ≥0) => B (ρ ω + t) ω - B (ρ ω) ω := by
  have hjoint : StronglyMeasurable (Function.uncurry B) :=
    stronglyMeasurable_uncurry_of_continuous_of_stronglyMeasurable hcont hm
  refine measurable_pi_lambda _ fun t => ?_
  exact (hjoint.measurable.comp ((hρ.add measurable_const).prodMk measurable_id)).sub
    (hjoint.measurable.comp (hρ.prodMk measurable_id))

/-- The restart identity at a stopping time with countably many values, as an identity of laws
on path space. -/
theorem IsBrownianSpace.map_shift_restrict_countable {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hB : IsBrownianSpace d x B P) (hm : ∀ t, StronglyMeasurable (B t))
    {σ : Ω → ℝ≥0}
    (hσ : IsStoppingTime (natFiltration B hm) fun ω => (σ ω : ℝ≥0∞))
    (hcount : (Set.range fun ω => ((σ ω : ℝ≥0) : ℝ≥0∞)).Countable)
    {E : Set Ω} (hE : MeasurableSet[hσ.measurableSpace] E)
    (hmσ : Measurable fun ω (t : ℝ≥0) => B (σ ω + t) ω - B (σ ω) ω) :
    Measure.map (fun ω (t : ℝ≥0) => B (σ ω + t) ω - B (σ ω) ω) (P.restrict E)
      = P E • Measure.map (fun ω (t : ℝ≥0) => B t ω - B 0 ω) P := by
  have hmm : ∀ t, Measurable (B t) := fun t => (hm t).measurable
  have hmshift0 : Measurable fun ω (t : ℝ≥0) => B t ω - B 0 ω :=
    measurable_pi_lambda _ fun t => (hmm t).sub (hmm 0)
  ext Γ hΓ
  rw [Measure.map_apply hmσ hΓ, Measure.restrict_apply (hmσ hΓ), Measure.smul_apply,
    Measure.map_apply hmshift0 hΓ, smul_eq_mul, Set.inter_comm]
  exact hB.restart_countable hm hσ hcount hE hΓ

theorem measure_cylinder_eq_map_restrict {ι : Type*} {α : ι → Type*}
    [∀ i, MeasurableSpace (α i)] (μ : Measure (∀ i, α i)) (J : Finset ι)
    {S : Set (∀ j : J, α j)} (hS : MeasurableSet S) :
    μ (cylinder J S) = (Measure.map J.restrict μ) S := by
  rw [Measure.map_apply (Finset.measurable_restrict J) hS]
  rfl

/-- **The strong Markov property of Brownian motion on `ℝ ^ d`.** -/
theorem IsBrownianSpace.hasStrongMarkovRestart {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hB : IsBrownianSpace d x B P) (hm : ∀ t, StronglyMeasurable (B t))
    (hcont : ∀ ω, Continuous fun t => B t ω) :
    HasStrongMarkovRestart B P (natFiltration B hm) where
  adapted := stronglyAdapted_natFiltration B hm
  restart := by
    haveI := hB.isProbabilityMeasure
    intro τ hτ E hE Γ hΓ
    have hmm : ∀ t, Measurable (B t) := fun t => (hm t).measurable
    have hτm : Measurable τ := measurable_of_isStoppingTime hτ
    have hmshift0 : Measurable fun ω (t : ℝ≥0) => B t ω - B 0 ω :=
      measurable_pi_lambda _ fun t => (hmm t).sub (hmm 0)
    have hmshiftτ : Measurable fun ω (t : ℝ≥0) => B (τ ω + t) ω - B (τ ω) ω :=
      measurable_shift_apply hm hcont hτm
    have hσst : ∀ n : ℕ, IsStoppingTime (natFiltration B hm)
        (fun ω => ((dyUp n (τ ω) : ℝ≥0) : ℝ≥0∞)) := fun n => isStoppingTime_dyUp hτ n
    have hσm : ∀ n : ℕ, Measurable fun ω => dyUp n (τ ω) := fun n =>
      measurable_of_isStoppingTime (hσst n)
    have hmshiftσ : ∀ n : ℕ, Measurable
        fun ω (t : ℝ≥0) => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω :=
      fun n => measurable_shift_apply hm hcont (hσm n)
    have hEσ : ∀ n : ℕ, MeasurableSet[(hσst n).measurableSpace] E := fun n =>
      hτ.measurableSpace_mono (hσst n) (fun ω => ENNReal.coe_le_coe.2 (le_dyUp n (τ ω))) _ hE
    have hlaw : ∀ n : ℕ,
        Measure.map (fun ω (t : ℝ≥0) => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω)
            (P.restrict E)
          = P E • Measure.map (fun ω (t : ℝ≥0) => B t ω - B 0 ω) P := fun n =>
      hB.map_shift_restrict_countable hm (hσst n) (countable_range_dyUp n τ) (hEσ n) (hmshiftσ n)
    set μ : Measure (ℝ≥0 → EuclideanSpace ℝ (Fin d)) :=
      Measure.map (fun ω (t : ℝ≥0) => B (τ ω + t) ω - B (τ ω) ω) (P.restrict E) with hμ
    set ν : Measure (ℝ≥0 → EuclideanSpace ℝ (Fin d)) :=
      P E • Measure.map (fun ω (t : ℝ≥0) => B t ω - B 0 ω) P with hν
    have hμuniv : μ Set.univ = P E := by
      rw [hμ, Measure.map_apply hmshiftτ MeasurableSet.univ, Set.preimage_univ,
        Measure.restrict_apply_univ]
    have hνuniv : ν Set.univ = P E := by
      rw [hν, Measure.smul_apply, Measure.map_apply hmshift0 MeasurableSet.univ,
        Set.preimage_univ, smul_eq_mul, measure_univ, mul_one]
    have hfinμ : μ Set.univ < ⊤ := by rw [hμuniv]; exact measure_lt_top _ _
    have hfinν : ν Set.univ < ⊤ := by rw [hνuniv]; exact measure_lt_top _ _
    haveI : IsFiniteMeasure μ := ⟨hfinμ⟩
    haveI : IsFiniteMeasure ν := ⟨hfinν⟩
    have hμν : μ = ν := by
      refine ext_of_generate_finite _ generateFrom_measurableCylinders.symm
        isPiSystem_measurableCylinders ?_ (hμuniv.trans hνuniv.symm)
      rintro s hs
      obtain ⟨J, S, hS, rfl⟩ := (mem_measurableCylinders s).mp hs
      have hmr : Measurable (J.restrict (π := fun _ : ℝ≥0 => EuclideanSpace ℝ (Fin d))) :=
        Finset.measurable_restrict J
      have hproj : Measure.map J.restrict μ = Measure.map J.restrict ν := by
        have hfin1 : (Measure.map J.restrict μ) Set.univ < ⊤ := by
          rw [Measure.map_apply hmr MeasurableSet.univ, Set.preimage_univ, hμuniv]
          exact measure_lt_top _ _
        have hfin2 : (Measure.map J.restrict ν) Set.univ < ⊤ := by
          rw [Measure.map_apply hmr MeasurableSet.univ, Set.preimage_univ, hνuniv]
          exact measure_lt_top _ _
        haveI : IsFiniteMeasure (Measure.map J.restrict μ) := ⟨hfin1⟩
        haveI : IsFiniteMeasure (Measure.map J.restrict ν) := ⟨hfin2⟩
        refine ext_of_forall_integral_eq_of_IsFiniteMeasure fun f => ?_
        have hfm : Measurable (f : (∀ j : J, EuclideanSpace ℝ (Fin d)) → ℝ) :=
          f.continuous.measurable
        have hL : ∫ y, f y ∂(Measure.map J.restrict μ)
            = ∫ ω, f (J.restrict (fun t => B (τ ω + t) ω - B (τ ω) ω)) ∂(P.restrict E) := by
          rw [hμ, Measure.map_map hmr hmshiftτ,
            integral_map (hmr.comp hmshiftτ).aemeasurable hfm.aestronglyMeasurable]
          rfl
        have hRn : ∀ n : ℕ, ∫ y, f y ∂(Measure.map J.restrict ν)
            = ∫ ω, f (J.restrict
                (fun t => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω)) ∂(P.restrict E) := by
          intro n
          rw [← hlaw n, Measure.map_map hmr (hmshiftσ n),
            integral_map (hmr.comp (hmshiftσ n)).aemeasurable hfm.aestronglyMeasurable]
          rfl
        have hdom : Tendsto (fun n : ℕ => ∫ ω, f (J.restrict
            (fun t => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω)) ∂(P.restrict E)) atTop
            (𝓝 (∫ ω, f (J.restrict (fun t => B (τ ω + t) ω - B (τ ω) ω)) ∂(P.restrict E))) := by
          refine tendsto_integral_of_dominated_convergence (fun _ => ‖f‖)
            (fun n => (hfm.comp (hmr.comp (hmshiftσ n))).aestronglyMeasurable)
            (integrable_const _) (fun n => Filter.Eventually.of_forall fun ω => ?_)
            (Filter.Eventually.of_forall fun ω => ?_)
          · exact f.norm_coe_le_norm _
          · exact (f.continuous.tendsto _).comp (tendsto_restrict_shift_dyUp hcont τ J ω)
        have hconst : Tendsto (fun n : ℕ => ∫ ω, f (J.restrict
            (fun t => B (dyUp n (τ ω) + t) ω - B (dyUp n (τ ω)) ω)) ∂(P.restrict E)) atTop
            (𝓝 (∫ y, f y ∂(Measure.map J.restrict ν))) := by
          simp only [← hRn]
          exact tendsto_const_nhds
        rw [hL]
        exact (tendsto_nhds_unique hconst hdom).symm
      rw [measure_cylinder_eq_map_restrict μ J hS, measure_cylinder_eq_map_restrict ν J hS, hproj]
    have hfin := congrArg (fun m : Measure (ℝ≥0 → EuclideanSpace ℝ (Fin d)) => m Γ) hμν
    simp only [hμ, hν] at hfin
    rw [Measure.map_apply hmshiftτ hΓ, Measure.restrict_apply (hmshiftτ hΓ), Measure.smul_apply,
      Measure.map_apply hmshift0 hΓ, smul_eq_mul] at hfin
    rw [Set.inter_comm]
    exact hfin


/-- The restart identity read off the strong Markov property, for the natural filtration. -/
theorem IsBrownianSpace.restart {d : ℕ}
    {x : EuclideanSpace ℝ (Fin d)} {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    (hB : IsBrownianSpace d x B P) (hm : ∀ t, StronglyMeasurable (B t))
    (hcont : ∀ ω, Continuous fun t => B t ω)
    (τ : Ω → ℝ≥0)
    (hτ : IsStoppingTime (natFiltration B hm) fun ω => (τ ω : ℝ≥0∞))
    (E : Set Ω) (hE : MeasurableSet[hτ.measurableSpace] E)
    (Γ : Set (ℝ≥0 → EuclideanSpace ℝ (Fin d))) (hΓ : MeasurableSet Γ) :
    P (E ∩ {ω | (fun t => B (τ ω + t) ω - B (τ ω) ω) ∈ Γ})
      = P E * P {ω | (fun t => B t ω - B 0 ω) ∈ Γ} := by
  exact (hB.hasStrongMarkovRestart hm hcont).restart τ hτ E hE Γ hΓ

end LatticeProb

end
