/-
Restarting Brownian motion.

At a deterministic time the restart is unconditional and is proved here: the
increments of a Brownian motion on `ℝ ^ d` after a time `t₀` are again a
Brownian motion, started at the origin, and each coordinate of the restarted
motion is independent of that coordinate before `t₀`.  The second statement is
Mathlib's weak Markov property `IsPreBrownianReal.indepFun_shift`, read through
the coordinates of `IsBrownianSpace`.

At a stopping time the restart is the strong Markov property, which Mathlib does
not have and which is not proved here.  It is stated, for a filtration to which
the motion is adapted, as `LatticeProb.HasStrongMarkovRestart`: the increments
after the stopping time have the law of the motion itself, centred, and are
independent of the past.  This is the form an optimal stopping argument needs:
with `E` the event that the exit time of a ball is before `T` and `Γ` a property
of the restarted path, it says that the restarted path may be replaced by a
fresh motion started at the stopping position.  What is proved about it here is
the consequence at `E = univ`, that the restarted increments have the law of the
motion, and that the property is stated for the σ-algebra Mathlib associates
with a stopping time, so that at a constant time it is the σ-algebra of the
filtration at that time.
-/
import Mathlib
import LatticeProb.Prob.BrownianExit

open MeasureTheory ProbabilityTheory Filter

open scoped ENNReal NNReal Topology

noncomputable section

namespace LatticeProb

variable {Ω : Type*} [MeasurableSpace Ω] {P : Measure Ω}

/-! ### Restarting at a deterministic time -/

/-- **The Markov property at a deterministic time.**  The increments of a Brownian motion on
`ℝ ^ d` after the time `t₀` are a Brownian motion started at the origin. -/
theorem IsBrownianSpace.shift {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)} (hB : IsBrownianSpace d x B P) (t₀ : ℝ≥0) :
    IsBrownianSpace d 0 (fun t ω => B (t₀ + t) ω - B t₀ ω) P where
  start := by
    filter_upwards with ω
    simp
  coord := by
    intro i
    have h := (hB.coord i).shift t₀
    have heq : (fun (t : ℝ≥0) (ω : Ω) => Real.sqrt d *
          ((B (t₀ + t) ω - B t₀ ω) i - (0 : EuclideanSpace ℝ (Fin d)) i))
        = fun (t : ℝ≥0) (ω : Ω) => Real.sqrt d * (B (t₀ + t) ω i - x i)
            - Real.sqrt d * (B t₀ ω i - x i) := by
      funext t ω
      simp only [PiLp.sub_apply, PiLp.zero_apply, sub_zero]
      ring
    rw [heq]
    exact h
  indep := by
    have h := hB.indep.comp (fun (_ : Fin d) (g : ℝ≥0 → ℝ) => fun t : ℝ≥0 => g (t₀ + t) - g t₀)
      (fun _ => measurable_pi_lambda _
        (fun t => (measurable_pi_apply (t₀ + t)).sub (measurable_pi_apply t₀)))
    exact h

/-- **The weak Markov property, coordinatewise.**  The increments of a coordinate after `t₀`
are independent of that coordinate before `t₀`.  This is Mathlib's
`IsPreBrownianReal.indepFun_shift` for the rescaled coordinate process. -/
theorem IsBrownianSpace.indepFun_coord_shift {d : ℕ} {x : EuclideanSpace ℝ (Fin d)}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)} (hB : IsBrownianSpace d x B P) (t₀ : ℝ≥0)
    (i : Fin d) :
    IndepFun (fun ω (t : ℝ≥0) => Real.sqrt d * (B (t₀ + t) ω i - B t₀ ω i))
      (fun ω (s : Set.Iic t₀) => Real.sqrt d * (B (s : ℝ≥0) ω i - x i)) P := by
  have h := (hB.coord i).toIsPreBrownianReal.indepFun_shift t₀
  have heq : (fun (ω : Ω) (t : ℝ≥0) => Real.sqrt d * (B (t₀ + t) ω i - x i)
        - Real.sqrt d * (B t₀ ω i - x i))
      = fun (ω : Ω) (t : ℝ≥0) => Real.sqrt d * (B (t₀ + t) ω i - B t₀ ω i) := by
    funext ω t
    ring
  rw [heq] at h
  exact h

/-! ### The natural filtration -/

/-- The natural filtration of a motion whose values are measurable: the σ-algebra at `t` is
generated by the path up to `t`, which is exactly the σ-algebra appearing in the weak Markov
property (`MeasureTheory.Filtration.natural_eq_comap`). -/
def natFiltration {d : ℕ} (B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d))
    (hB : ∀ t, StronglyMeasurable (B t)) :
    Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω) :=
  Filtration.natural B hB

theorem stronglyAdapted_natFiltration {d : ℕ} (B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d))
    (hB : ∀ t, StronglyMeasurable (B t)) : StronglyAdapted (natFiltration B hB) B :=
  Filtration.stronglyAdapted_natural hB

theorem natFiltration_eq_comap {d : ℕ} (B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d))
    (hB : ∀ t, StronglyMeasurable (B t)) (t : ℝ≥0) :
    natFiltration B hB t
      = MeasurableSpace.comap (fun ω (s : Set.Iic t) => B (s : ℝ≥0) ω) inferInstance :=
  Filtration.natural_eq_comap B hB t

/-! ### Restarting at a stopping time -/

/-- **The strong Markov property at a stopping time**, for a filtration `𝔽`.  For every
stopping time `τ` of `𝔽`, every event `E` of the past at `τ` and every measurable set `Γ` of
paths, the restarted increments `t ↦ B (τ + t) - B τ` lie in `Γ` with the probability that
the centred motion itself does, independently of `E`.

This is what an optimal stopping argument asks for at the exit time of a ball: the value
gained after the exit time is the value of a motion started afresh at the exit position, so
the excess of the free value over the value localized to the ball is the probability of
leaving the ball times the value at the exit position.

It is a hypothesis: Mathlib 4.32 has the Markov property at a deterministic time
(`IsPreBrownianReal.indepFun_shift`, used above) and no strong Markov property.  A proof
runs through stopping times with countably many values, where the identity follows from the
deterministic case applied on each of the countably many events `{τ = t}`, and then through
the almost sure continuity of the paths. -/
def HasStrongMarkovRestart {d : ℕ} (B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)) (P : Measure Ω)
    (𝔽 : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)) : Prop :=
  ∀ (τ : Ω → ℝ≥0) (hτ : IsStoppingTime 𝔽 fun ω => (τ ω : ℝ≥0∞)),
    ∀ E : Set Ω, MeasurableSet[hτ.measurableSpace] E →
      ∀ Γ : Set (ℝ≥0 → EuclideanSpace ℝ (Fin d)), MeasurableSet Γ →
        P (E ∩ {ω | (fun t => B (τ ω + t) ω - B (τ ω) ω) ∈ Γ})
          = P E * P {ω | (fun t => B t ω - B 0 ω) ∈ Γ}

/-- The law of the restarted increments is the law of the centred motion: the strong Markov
property at the whole space. -/
theorem HasStrongMarkovRestart.law [IsProbabilityMeasure P] {d : ℕ}
    {B : ℝ≥0 → Ω → EuclideanSpace ℝ (Fin d)}
    {𝔽 : Filtration ℝ≥0 (inferInstance : MeasurableSpace Ω)}
    (h : HasStrongMarkovRestart B P 𝔽) (τ : Ω → ℝ≥0)
    (hτ : IsStoppingTime 𝔽 fun ω => (τ ω : ℝ≥0∞))
    (Γ : Set (ℝ≥0 → EuclideanSpace ℝ (Fin d))) (hΓ : MeasurableSet Γ) :
    P {ω | (fun t => B (τ ω + t) ω - B (τ ω) ω) ∈ Γ}
      = P {ω | (fun t => B t ω - B 0 ω) ∈ Γ} := by
  have hE := h τ hτ Set.univ MeasurableSet.univ Γ hΓ
  rwa [Set.univ_inter, measure_univ, one_mul] at hE

end LatticeProb

end
