/-
Independence of two families of random variables read coordinate by coordinate.

The situation is the one a product of independent processes creates: for each
index `i` there is a pair of random variables `(f i, g i)`, the pairs are
independent across `i`, and inside each pair the two components are independent.
The conclusion is that the whole family `f` is independent of the whole family
`g`.  It does not follow from either hypothesis alone, and the proof is the
π-system computation

  P (⋂ i, A i ∩ B i) = ∏ i, P (A i ∩ B i) = ∏ i, P (A i) * P (B i)
                     = (∏ i, P (A i)) * ∏ i, P (B i) = P (⋂ i, A i) * P (⋂ i, B i),

whose first and last steps are the independence of the pairs and whose middle
step is the independence inside each pair.  The π-system is `interBoxes`, the
intersections of one event from each σ-algebra of a family; it generates the
supremum of the family because an event of one member is the intersection with
the whole space in every other coordinate.
-/
import Mathlib

open MeasureTheory ProbabilityTheory Filter

open scoped ENNReal NNReal Topology

noncomputable section

namespace LatticeProb

variable {Ω : Type*} {m0 : MeasurableSpace Ω}

/-- The events that are an intersection of one event from each member of a family of
σ-algebras. -/
def interBoxes {ι : Type*} (𝒜 : ι → MeasurableSpace Ω) : Set (Set Ω) :=
  {s | ∃ A : ι → Set Ω, (∀ i, MeasurableSet[𝒜 i] (A i)) ∧ s = ⋂ i, A i}

theorem isPiSystem_interBoxes {ι : Type*} (𝒜 : ι → MeasurableSpace Ω) :
    IsPiSystem (interBoxes 𝒜) := by
  rintro s ⟨A, hA, rfl⟩ t ⟨B, hB, rfl⟩ -
  refine ⟨fun i => A i ∩ B i, fun i => (hA i).inter (hB i), ?_⟩
  ext x
  simp only [Set.mem_inter_iff, Set.mem_iInter]
  exact forall_and.symm

/-- The intersections generate the supremum of the family: an event of one member is the
intersection that takes the whole space in every other coordinate. -/
theorem generateFrom_interBoxes {ι : Type*} [Countable ι] (𝒜 : ι → MeasurableSpace Ω) :
    MeasurableSpace.generateFrom (interBoxes 𝒜) = ⨆ i, 𝒜 i := by
  classical
  refine le_antisymm (MeasurableSpace.generateFrom_le ?_) (iSup_le fun i => ?_)
  · rintro s ⟨A, hA, rfl⟩
    exact MeasurableSet.iInter fun i => (le_iSup 𝒜 i) _ (hA i)
  · intro s hs
    have hrw : s = ⋂ j, (if j = i then s else Set.univ) := by
      ext x
      simp only [Set.mem_iInter]
      constructor
      · intro hx j
        by_cases hj : j = i
        · simpa [hj] using hx
        · simp [hj]
      · intro hx
        simpa using hx i
    rw [hrw]
    refine MeasurableSpace.measurableSet_generateFrom
      ⟨fun j => if j = i then s else Set.univ, fun j => ?_, rfl⟩
    by_cases hj : j = i
    · subst hj
      simpa using hs
    · simp [hj]

/-- **Independent pairs give independent families.**  If the pairs `(𝒜 i, ℬ i)` are independent
across `i`, and `𝒜 i` is independent of `ℬ i` for each `i`, then `⨆ i, 𝒜 i` is independent of
`⨆ i, ℬ i`. -/
theorem indep_iSup_of_pairs {ι : Type*} [Fintype ι] {𝒜 ℬ : ι → MeasurableSpace Ω}
    {P : Measure Ω} [IsProbabilityMeasure P]
    (h𝒜 : ∀ i, 𝒜 i ≤ m0) (hℬ : ∀ i, ℬ i ≤ m0)
    (hpair : iIndep (fun i => 𝒜 i ⊔ ℬ i) P)
    (hin : ∀ i, Indep (𝒜 i) (ℬ i) P) :
    Indep (⨆ i, 𝒜 i) (⨆ i, ℬ i) P := by
  refine IndepSets.indep (iSup_le h𝒜) (iSup_le hℬ)
    (isPiSystem_interBoxes 𝒜) (isPiSystem_interBoxes ℬ)
    (generateFrom_interBoxes 𝒜).symm (generateFrom_interBoxes ℬ).symm ((IndepSets_iff _ _ _).2 ?_)
  rintro s t ⟨A, hA, rfl⟩ ⟨Bs, hB, rfl⟩
  have hAm : ∀ i, MeasurableSet[𝒜 i ⊔ ℬ i] (A i) :=
    fun i => (le_sup_left : 𝒜 i ≤ 𝒜 i ⊔ ℬ i) _ (hA i)
  have hBm : ∀ i, MeasurableSet[𝒜 i ⊔ ℬ i] (Bs i) :=
    fun i => (le_sup_right : ℬ i ≤ 𝒜 i ⊔ ℬ i) _ (hB i)
  have hABm : ∀ i, MeasurableSet[𝒜 i ⊔ ℬ i] (A i ∩ Bs i) := fun i => (hAm i).inter (hBm i)
  have hinter : (⋂ i, A i) ∩ (⋂ i, Bs i) = ⋂ i, (A i ∩ Bs i) := by
    ext x; simp only [Set.mem_inter_iff, Set.mem_iInter]; exact forall_and.symm
  rw [hinter, ProbabilityTheory.iIndep.meas_iInter hpair hABm,
    ProbabilityTheory.iIndep.meas_iInter hpair hAm,
    ProbabilityTheory.iIndep.meas_iInter hpair hBm, ← Finset.prod_mul_distrib]
  exact Finset.prod_congr rfl fun i _ => (Indep_iff _ _ _).1 (hin i) _ _ (hA i) (hB i)

/-- The σ-algebra generated by a map into a product is the supremum of those generated by its
coordinates. -/
theorem comap_pi_eq_iSup {ι : Type*} {β : ι → Type*} [∀ i, MeasurableSpace (β i)]
    (f : ∀ i, Ω → β i) :
    MeasurableSpace.comap (fun ω i => f i ω) MeasurableSpace.pi
      = ⨆ i, MeasurableSpace.comap (f i) inferInstance := by
  rw [show (MeasurableSpace.pi : MeasurableSpace (∀ i, β i))
        = ⨆ i, MeasurableSpace.comap (fun b : ∀ i, β i => b i) inferInstance from rfl,
    MeasurableSpace.comap_iSup]
  exact iSup_congr fun i => MeasurableSpace.comap_comp

/-- The σ-algebra generated by a pair is the supremum of those generated by its components. -/
theorem comap_prodMk_eq_sup {β γ : Type*} [MeasurableSpace β] [MeasurableSpace γ]
    (f : Ω → β) (g : Ω → γ) :
    MeasurableSpace.comap (fun ω => (f ω, g ω)) inferInstance
      = MeasurableSpace.comap f inferInstance ⊔ MeasurableSpace.comap g inferInstance := by
  rw [show (inferInstance : MeasurableSpace (β × γ))
        = MeasurableSpace.comap Prod.fst inferInstance
          ⊔ MeasurableSpace.comap Prod.snd inferInstance from rfl,
    MeasurableSpace.comap_sup, MeasurableSpace.comap_comp, MeasurableSpace.comap_comp]
  rfl

/-- **Independent pairs give independent families**, in the form for random variables: if the
pairs `(f i, g i)` are independent across `i` and the two components of each pair are
independent, then the family `f` is independent of the family `g`. -/
theorem indepFun_pi_of_pairs {ι : Type*} [Fintype ι] {β γ : ι → Type*}
    [∀ i, MeasurableSpace (β i)] [∀ i, MeasurableSpace (γ i)]
    {P : Measure Ω} [IsProbabilityMeasure P] {f : ∀ i, Ω → β i} {g : ∀ i, Ω → γ i}
    (hf : ∀ i, Measurable (f i)) (hg : ∀ i, Measurable (g i))
    (hpair : iIndepFun (fun i ω => (f i ω, g i ω)) P)
    (hin : ∀ i, IndepFun (f i) (g i) P) :
    IndepFun (fun ω i => f i ω) (fun ω i => g i ω) P := by
  rw [IndepFun_iff_Indep, comap_pi_eq_iSup, comap_pi_eq_iSup]
  refine indep_iSup_of_pairs (fun i => (hf i).comap_le) (fun i => (hg i).comap_le) ?_ ?_
  · have h := hpair.iIndep
    simpa only [comap_prodMk_eq_sup] using h
  · exact fun i => (IndepFun_iff_Indep _ _ _).mp (hin i)

end LatticeProb

end
